name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7

        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
          
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Executar Migrations e Testes
      env:
        NODE_ENV: test
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        DB_TEST_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
      run: |
        # Executa as migrações para criar as tabelas no banco de dados de teste
        npx sequelize-cli db:migrate --env test
        # Executa os testes
        npm test
        
    - name: Executar Lint
      run: npm run lint
