name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start MySQL
      run: sudo /etc/init.d/mysql start

    - name: Configure Test Database
      run: |
        mysql -uroot -proot -e "CREATE DATABASE student_manager_test;"
        mysql -uroot -proot -e "CREATE USER 'testuser'@'localhost' IDENTIFIED BY 'testpass';"
        mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON student_manager_test.* TO 'testuser'@'localhost';"
        mysql -uroot -proot -e "FLUSH PRIVILEGES;"

    - run: npm ci
      env:
        NODE_ENV: test
        DB_USERNAME: testuser
        DB_PASSWORD: testpass
        DB_DATABASE: student_manager_test
        DB_HOST: 127.0.0.1
        DB_DIALECT: mysql

    - run: npm run lint

    - run: npm test
      env:
        NODE_ENV: test
        DB_USERNAME: testuser
        DB_PASSWORD: testpass
        DB_DATABASE: student_manager_test
        DB_HOST: 127.0.0.1
        DB_DIALECT: mysql