name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Inicia o serviço do MySQL com a configuração mínima e essencial
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        ports:
          - 3306:3306

    strategy:
      matrix:
        # Mantendo a versão 18.x do Node.js para compatibilidade com o ESLint
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Wait for MySQL
      # Pausa o workflow por 15 segundos para dar tempo ao MySQL de iniciar
      run: sleep 15

    - name: Run Migrations
      env:
        DATABASE_URL_TEST: mysql://root:${{ secrets.DB_TEST_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_TEST_DATABASE }}
      run: npx sequelize-cli db:migrate --env test

    - name: Run Lint
      run: npm run lint

    - name: Run tests
      env:
        NODE_ENV: test
        DATABASE_URL_TEST: mysql://root:${{ secrets.DB_TEST_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_TEST_DATABASE }}
      run: npm test