name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
        ports:
          - 3306:3306

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Wait for MySQL
      run: sleep 15

    - name: Run Migrations and Tests
      # Passa as variáveis de ambiente necessárias para os comandos
      env:
        NODE_ENV: test
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        DB_TEST_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
      run: |
        npx sequelize-cli db:migrate --env test
        npm test
        
    - name: Run Lint
      run: npm run lint